export const TRANSFER_KEYWORDS = [
  'transfer',
  'p2p',
  'card to card',
  'c2c',
  'perevod',
  'perekaz',
  'перевод',
  'переказ',
  'переказ на картку',
  'переказ на рахунок',
  'переказ між',
  'між своїми',
  'між власними',
  'власними рахунками',
  'мій рахунок',
  'my account',
  'з рахунку',
  'з картки',
  'з єврової картки',
  'з гривневого рахунку',
  'from account',
  'to account',
  'продаж валюти',
  'купівля валюти',
  'обмін валюти',
  'sale of currency',
  'purchase of currency',
  'currency exchange',
  'за договором',
  'для переказу на картку',
  'на чорну картку',
  'на білу картку',
  'на гривневий рахунок фоп',
  'на євровий рахунок',
  'з єврового рахунку фоп',
];

export const TRANSFER_EXCLUDE_KEYWORDS = [
  'cashback',
  'кешбек',
  'кешбэк',
  'bonus',
  'reward',
  'скасув',
  'cancellation',
];

export const TRANSFER_MCC_STRICT = new Set([6536, 6537, 6538, 6540]);
export const TRANSFER_MCC_KEYWORD = new Set([4829, 6012, 6051]);
