import { TransactionType, type DefaultCategoryData } from './finance-categories.types';

export const DEFAULT_FINANCE_EXPENSE_PRIMARY_CATEGORIES: DefaultCategoryData[] = [
  {
    name: 'Food & Dining',
    type: TransactionType.EXPENSE,
    color: '#EF4444',
    icon: 'UtensilsCrossed',
    isDefault: true,
    children: [
      {
        name: 'Groceries',
        type: TransactionType.EXPENSE,
        color: '#DC2626',
        icon: 'ShoppingBasket',
        isDefault: true,
      },
      {
        name: 'Restaurants',
        type: TransactionType.EXPENSE,
        color: '#B91C1C',
        icon: 'UtensilsCrossed',
        isDefault: true,
      },
    ],
  },
  {
    name: 'Transportation',
    type: TransactionType.EXPENSE,
    color: '#06B6D4',
    icon: 'Car',
    isDefault: true,
    children: [
      {
        name: 'Fuel',
        type: TransactionType.EXPENSE,
        color: '#0891B2',
        icon: 'Fuel',
        isDefault: true,
      },
      {
        name: 'Public Transport',
        type: TransactionType.EXPENSE,
        color: '#0E7490',
        icon: 'Bus',
        isDefault: true,
      },
      {
        name: 'Car Maintenance',
        type: TransactionType.EXPENSE,
        color: '#164E63',
        icon: 'Wrench',
        isDefault: true,
      },
      {
        name: 'Parking',
        type: TransactionType.EXPENSE,
        color: '#155E75',
        icon: 'Square',
        isDefault: true,
      },
    ],
  },
  {
    name: 'Housing',
    type: TransactionType.EXPENSE,
    color: '#84CC16',
    icon: 'Home',
    isDefault: true,
    children: [
      {
        name: 'Rent/Mortgage',
        type: TransactionType.EXPENSE,
        color: '#65A30D',
        icon: 'Key',
        isDefault: true,
      },
      {
        name: 'Utilities',
        type: TransactionType.EXPENSE,
        color: '#4D7C0F',
        icon: 'Zap',
        isDefault: true,
      },
      {
        name: 'Home Maintenance',
        type: TransactionType.EXPENSE,
        color: '#365314',
        icon: 'Hammer',
        isDefault: true,
      },
    ],
  },
  {
    name: 'Healthcare',
    type: TransactionType.EXPENSE,
    color: '#EC4899',
    icon: 'Heart',
    isDefault: true,
    children: [
      {
        name: 'Medical Services',
        type: TransactionType.EXPENSE,
        color: '#DB2777',
        icon: 'Stethoscope',
        isDefault: true,
      },
      {
        name: 'Medications',
        type: TransactionType.EXPENSE,
        color: '#BE185D',
        icon: 'Pill',
        isDefault: true,
      },
      {
        name: 'Dental',
        type: TransactionType.EXPENSE,
        color: '#9D174D',
        icon: 'Smile',
        isDefault: true,
      },
      {
        name: 'Health Insurance',
        type: TransactionType.EXPENSE,
        color: '#831843',
        icon: 'Shield',
        isDefault: true,
      },
    ],
  },
  {
    name: 'Entertainment',
    type: TransactionType.EXPENSE,
    color: '#F97316',
    icon: 'Music',
    isDefault: true,
  },
  {
    name: 'Shopping',
    type: TransactionType.EXPENSE,
    color: '#A855F7',
    icon: 'ShoppingBag',
    isDefault: true,
    children: [
      {
        name: 'Clothing',
        type: TransactionType.EXPENSE,
        color: '#9333EA',
        icon: 'Shirt',
        isDefault: true,
      },
      {
        name: 'Electronics',
        type: TransactionType.EXPENSE,
        color: '#7C3AED',
        icon: 'Smartphone',
        isDefault: true,
      },
      {
        name: 'Home & Garden',
        type: TransactionType.EXPENSE,
        color: '#6D28D9',
        icon: 'Home',
        isDefault: true,
      },
      {
        name: 'Personal Care',
        type: TransactionType.EXPENSE,
        color: '#5B21B6',
        icon: 'Sparkles',
        isDefault: true,
      },
    ],
  },
];
